name: Deploy Geo And Dent media theme  to DotNest

on:
  push:
    branches:
      - geo-dent
    paths:
      - 'src/Themes/GeoAndDent.Theme/**'

jobs:
  deploy-media-theme:
    uses: Lombiq/Hosting-Media-Theme/.github/workflows/deploy-media-theme.yml@dev
    secrets:
      URL: ${{ secrets.GEO_DENT_DEPLOYMENT_URL }}
      CLIENT_NAME: ${{ secrets.GEO_DENT_DEPLOYMENT_CLIENT_NAME }}
      CLIENT_API_KEY: ${{ secrets.GEO_DENT_DEPLOYMENT_CLIENT_API_KEY }}
    with:
      theme-path: "src/Themes/GeoAndDent.Theme"
